server:
  port: ${HOST_PORT:8080}

spring:
  application:
    name: naeo-2023
  datasource:
    generate-unique-name: false
    name: naeo-2023
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    show-sql: true

springdoc:
  swagger-ui:
    url: "/api-docs/v1"
    path: /swagger-ui.html
  api-docs:
    path: /api-docs/v1
    enabled: true