server:
  port: ${HOST_PORT:8080}

spring:
  application:
    name: naeo-2023
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    show-sql: true

springdoc:
  swagger-ui:
    url: "/api-docs"
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
    enabled: true